sonar.projectKey=developerdurp_durpdeploy-agent
sonar.organization=developerdurp
sonar.go.coverage.reportPaths=coverage.out
sonar.sources=.
sonar.exclusions=**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go
